cache:
  apt: true
  pip: true

jobs:
  include:
    - name: "C++ Lib Testing"
      language: cpp
      os: linux
      dist: Bionic
      compiler: gcc
      addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
          - gcc-8
          - gfortran-8
        env:
          - CXX='g++-8'
          - CC='gcc-8'
          - CFLAGS='-DNRUNS=100000000'
      script:
        - sudo apt update
        - sudo apt install libsfml-dev
        - cd C++
        - make test

    - name: "Python Lib Testing"
      language: python
      script:
        - cd Python3 
        - pip3 freeze — local | grep -v ‘^\-e’ | cut -d = -f 1 | xargs -n1 pip3 install -U
        - pip install pylint
        - pip install -r requirements.txt
        - pylint -E Pylibtitan.py